version: '3.7'

services:
  currency-exchange:
    image: anadi231/image-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - rabbitmq    
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseurl: http://zipkin-server:9411/
      rabbit_uri: amqp:guest:guest@rabbitmq:5672
      spring_rabbitmq_host: rabbitmq
      spring_zipkin-sender_type: rabbit
      
  currency-conversion:
    image: anadi231/image-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka  
      spring.zipkin.baseurl: http://zipkin-server:9411/
      rabbit_uri: amqp:guest:guest@rabbitmq:5672
      spring_rabbitmq_host: rabbitmq
      spring_zipkin-sender_type: rabbit

  api-gateway:
    image: anadi231/image-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka   
      spring.zipkin.baseurl: http://zipkin-server:9411/
      rabbit_uri: amqp:guest:guest@rabbitmq:5672
      spring_rabbitmq_host: rabbitmq
      spring_zipkin-sender_type: rabbit      
  
  naming-server:
    image: anadi231/image-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"   
    
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 700m
    ports:
      - "9411:9411"
    depends_on:
      - rabbitmq
    environment:
      rabbit_uri: amqp:guest:guest@rabbitmq:5672          
      
  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_limit: 700m
    ports:
      - "5672:5672"       
      
      
      
      
      
      
      
      
      
      